name: demucs2

channels:
  - pytorch
  - conda-forge
  - nvidia

dependencies:
  - python>=3.7,<3.9
  - ffmpeg>=4.2
  - pytorch==2.3.1
  - torchaudio==2.3.1
  - pytorch-cuda==12.1
  - tqdm>=4.36
  - pip
  - pip:
    - diffq<0.2.0
    - julius>=0.2.3
    - lameenc>=1.2
    - musdb==0.4.0
    - museval>=0.4.0
    - soundfile
    - treetable>=0.2.3
    - stempeg==0.2.3
